---
title: "Introduction to RStudio"
output: html_document
date: "2026-02-08"
---

# PART 1

### Load the necessary packages:

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(gapminder)
library(plotly)
```

## SUMMARY STATS

### 1. How many countries are in each **continent**?




### Fixing the Duplicates




### 2. Find the average life expectancy in each continent.





### 3. Find the average life expectancy and median life expectancy for each continent for the years after 1980.






### 4. Find the correlation between life expectancy and GDP for each continent






# PART 2

------------------------------------------------------------------------

## PLOTS

### 1. Draw a bar chart to represent the number of countries in each continent






### Fixing the double counting issue






### 2. Draw a histogram of life expectancy values




### 3. Draw a density plot of life expectancy values






### 4. Draw a line chart (time series plot) to represent how life expectancy has changed over time





### Fixing the issue





### A More Clearer View






### Do the same time series plot only for Asia and Africa





### 5. Draw a scatterplot to represent the relationship between GDP and life expectancy






### Add country name as a text mapping






### Remove Kuwait and Saudi Arabia







### Add more than one filter:






